# -*- coding: utf-8 -*-
"""Modelo de recomendacion dv y gm

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Mx7ScmAPKcuXYPnJfOggyTHKfi24R3OV

# Modelo Predictivo para la Recomendación de Oportunidades Laborales en el Ámbito Gubernamental

Autor: Diana Vásquez- Germám Mahecha
Maestría: Ciencia de datos

Objetivo

Desarrollar un modelo predictivo utilizando técnicas de Machine Learning que permita recomendar oportunidades laborales a partir de la información de aspirantes y vacantes públicas.

##Módulo 1. Carga de librerías

Este módulo prepara el entorno de trabajo para la construcción de la Analytical Base Table (ABT). Se importan las librerías necesarias para la manipulación de datos, visualización y preprocesamiento que serán utilizadas durante las diferentes etapas del proyecto.
"""

# ============================================================
# MÓDULO 1. CONFIGURACIÓN DEL ENTORNO
# Construcción de la Analytical Base Table (ABT)
# ============================================================

# Manipulación de datos
import pandas as pd
import numpy as np

# Visualización
import matplotlib.pyplot as plt
import seaborn as sns

# Configuración de visualización
pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', 100)
pd.set_option('display.width', None)
pd.set_option('display.max_colwidth', 120)

# Configuración de gráficos
plt.style.use("ggplot")

# Ignorar advertencias
import warnings
warnings.filterwarnings("ignore")

print("✔ Librerías cargadas correctamente.")

"""Este primer módulo tiene como finalidad establecer un entorno de trabajo homogéneo y reproducible, garantizando que todas las etapas posteriores de exploración, transformación e integración de los datos se desarrollen bajo una configuración consistente. La importación de las librerías y la definición de parámetros de visualización facilitan la inspección de los datos y mejoran la legibilidad de los resultados obtenidos durante la construcción de la ABT.

##Módulo 2. Carga y validación inicial de los conjuntos de datos

Cargar los tres conjuntos de datos que conformarán la base analítica del proyecto y realizar una validación inicial de su estructura. En esta etapa se verifica la correcta lectura de los archivos, se normalizan los nombres de las columnas y se inspeccionan las dimensiones y tipos de datos para asegurar la consistencia antes de iniciar el análisis exploratorio y la integración de la información.

###2.1. Cargar los datasets
"""

import pandas as pd

# ============================================================
# MÓDULO 2. CARGA DE LOS CONJUNTOS DE DATOS
# ============================================================

# Los archivos fueron exportados en formato CSV separado por ';'.
# Se utiliza la codificación UTF-8 con BOM y el motor de Python para
# garantizar una lectura correcta de los campos de texto.

formacion = pd.read_csv(
    "/content/Formacion2.csv",
    encoding="utf-8-sig",
    sep=";",
    quotechar='"',
    doublequote=True,
    engine="python"
)

# --- INICIO DE LA CORRECCIÓN ---
# El archivo Formacion2.csv se cargó incorrectamente creando un MultiIndex.
# Reseteamos el índice para convertir los niveles del MultiIndex en columnas.
# Se añade 'drop=True' para evitar que reset_index() cree una columna 'index' adicional.
formacion = formacion.reset_index(drop=True)

# Renombramos las columnas a sus nombres correctos, inferidos de la descripción del dataset
formacion.columns = [
    "postulante",
    "nivel_educativo",
    "municipio_residencia",
    "departamento_residencia",
    "titulo_academico",
    "area_conocimiento",
    "codigo_nbc", # Anteriormente 'unnamed: 0'
    "nivel_formacion" # Anteriormente 'especializacion profesional'
]
# --- FIN DE LA CORRECCIÓN ---

experiencia = pd.read_csv(
    "/content/Experiencia2.csv",
    encoding="utf-8-sig",
    sep=";",
    quotechar='"',
    doublequote=True,
    engine="python"
)

postulaciones = pd.read_csv(
    "/content/Postulaciones2.csv",
    encoding="utf-8-sig",
    sep=";",
    quotechar='"',
    doublequote=True,
    engine="python",
    on_bad_lines="skip"
)

print("✔ Archivos cargados correctamente.")

from google.colab import drive
drive.mount('/content/drive')

"""###2.2. Normalizar nombres de columnas"""

# Eliminar espacios y convertir nombres de columnas a minúsculas
formacion.columns = formacion.columns.str.strip().str.lower()
experiencia.columns = experiencia.columns.str.strip().str.lower()
postulaciones.columns = postulaciones.columns.str.strip().str.lower()

print("✔ Nombres de columnas normalizados.")

"""###2.3. Verificar dimensiones"""

print("Dimensiones de los datasets")

print(f"Formación      : {formacion.shape}")
print(f"Experiencia    : {experiencia.shape}")
print(f"Postulaciones  : {postulaciones.shape}")

"""###2.4. Visualizar las primeras filas"""

print("===== Formación =====")
display(formacion.head())

print("===== Experiencia =====")
display(experiencia.head())

print("===== Postulaciones =====")
display(postulaciones.head())

"""Análisis de la estructura de los datasets

1. Dataset Formación

| Variable                  | Observación                                                          |
| ------------------------- | -------------------------------------------------------------------- |
| `postulante`              | Identificador para la integración.                                   |
| `nivel_educativo`         | Nivel máximo reportado por el aspirante.                             |
| `municipio_residencia`    | Variable geográfica.                                                 |
| `departamento_residencia` | Variable geográfica.                                                 |
| `titulo_academico`        | Formación específica registrada.                                     |
| `codigo_nbc`              | Núcleo Básico del Conocimiento. Presenta valores nulos.              |
| `area_conocimiento`       | Área del conocimiento. Presenta valores nulos.                       |
| `nivel_formacion`         | Tipo de formación (Bachiller, Tecnológico, Formación Laboral, etc.). |

Hallazgos
Cada fila representa una formación académica del postulante.
Un postulante puede tener múltiples registros.
Los valores nulos en codigo_nbc y area_conocimiento son esperados para niveles como bachillerato o formación laboral.

Conclusión
Este dataset será la base para construir el perfil académico del postulante.

2. Dataset Experiencia

| Variable                    | Observación                             |
| --------------------------- | --------------------------------------- |
| `postulante`                | Identificador.                          |
| `experiencia_fecha_ingreso` | Fecha de inicio de la experiencia.      |
| `experiencia_fecha_salida`  | Fecha de finalización.                  |
| `tipo_experiencia`          | En la muestra aparece como "No aplica". |

Hallazgos
Existe un registro de experiencia por postulante en la muestra observada.
Las fechas permitirán calcular la duración de la experiencia laboral.
Será necesario convertir ambas columnas al tipo datetime.

Conclusión
Este dataset permitirá construir las variables de experiencia laboral sin necesidad de consolidar múltiples registros, salvo que detectemos postulantes repetidos.

3. Dataset Postulaciones

| Variable                       | Observación                                |
| ------------------------------ | ------------------------------------------ |
| `postulante`                   | Identificador.                             |
| `id`                           | Identificador de la convocatoria o empleo. |
| `empleo`                       | Descripción textual del cargo.             |
| `requisito_estudio`            | Requisitos académicos.                     |
| `requisito_experiencia`        | Requisitos de experiencia.                 |
| `requisito_tiempo_experiencia` | Tiempo mínimo exigido.                     |
| `tipo_prueba`                  | Etapa del proceso de selección.            |
| `aprobo`                       | Resultado de la prueba.                    |
| `calificacion`                 | Se observa vacía en la muestra.            |


Hallazgos
El resultado de interés es la variable aprobo, que podría utilizarse como variable objetivo.
Las columnas empleo, requisito_estudio y requisito_experiencia contienen texto descriptivo con un alto potencial para análisis mediante PLN.
calificacion parece no estar diligenciada; lo confirmaremos en el análisis de calidad.

Conclusión
Este dataset aporta el contexto de la postulación y el resultado del proceso de selección.

###2.5. Verificar la estructura de cada dataset
"""

print("===== Formación =====")
formacion.info()

print("\n===== Experiencia =====")
experiencia.info()

print("\n===== Postulaciones =====")
postulaciones.info()

"""###2.6. Resumen general de los datasets"""

def resumen_dataset(df, nombre):

    resumen = pd.DataFrame({
        "Variable": df.columns,
        "Tipo": df.dtypes.astype(str),
        "No nulos": df.notnull().sum(),
        "Nulos": df.isnull().sum(),
        "% Nulos": round(df.isnull().mean()*100,2)
    })

    print("="*70)
    print(nombre.upper())
    print("="*70)

    display(resumen)

resumen_dataset(formacion,"Formación")
resumen_dataset(experiencia,"Experiencia")
resumen_dataset(postulaciones,"Postulaciones")

"""##Módulo 3. Análisis de la estructura de los datos

Verificar la cardinalidad de cada conjunto de datos para determinar si cada postulante posee un único registro o múltiples registros. Este análisis permitirá definir la estrategia de construcción de la ABT, identificando los conjuntos de datos que requieren consolidación antes de su integración.

###3.1. Número de registros y postulantes únicos
"""

# ============================================================
# PASO 3.1. REGISTROS Y POSTULANTES ÚNICOS
# ============================================================

def resumen_postulantes(df, nombre):

    total_registros = len(df)
    postulantes_unicos = df["postulante"].nunique()

    print("="*70)
    print(nombre.upper())
    print("="*70)
    print(f"Total de registros      : {total_registros:,}")
    print(f"Postulantes únicos      : {postulantes_unicos:,}")
    print(f"Registros por postulante: {total_registros/postulantes_unicos:.2f}")
    print()

resumen_postulantes(formacion,"Formación")
resumen_postulantes(experiencia,"Experiencia")
resumen_postulantes(postulaciones,"Postulaciones")

"""###3.2. Distribución de registros por postulante"""

# ============================================================
# PASO 3.2. REGISTROS POR POSTULANTE
# ============================================================

def registros_por_postulante(df, nombre):

    print("="*70)
    print(nombre.upper())
    print("="*70)

    conteo = df.groupby("postulante").size()

    print(conteo.describe())

    print("\nFrecuencia de registros por postulante")

    display(conteo.value_counts().sort_index())

registros_por_postulante(formacion,"Formación")
registros_por_postulante(experiencia,"Experiencia")
registros_por_postulante(postulaciones,"Postulaciones")

"""###3.3. Identificar postulantes con más de un registro"""

# ============================================================
# PASO 3.3. POSTULANTES CON MÚLTIPLES REGISTROS
# ============================================================

def multiples_registros(df, nombre):

    conteo = df.groupby("postulante").size()

    multiples = conteo[conteo > 1]

    print("="*70)
    print(nombre.upper())
    print("="*70)

    print(f"Postulantes con más de un registro: {len(multiples):,}")

    if len(multiples) > 0:
        display(multiples.head(10))

multiples_registros(formacion,"Formación")
multiples_registros(experiencia,"Experiencia")
multiples_registros(postulaciones,"Postulaciones")

"""###3.4. Análisis de intersección entre los datasets

####3.4.1. Obtener los postulantes únicos
"""

# ============================================================
# PASO 3.4.1. POSTULANTES ÚNICOS POR DATASET
# ============================================================

post_formacion = set(formacion["postulante"].unique())
post_experiencia = set(experiencia["postulante"].unique())
post_postulaciones = set(postulaciones["postulante"].unique())

print(f"Postulantes Formación     : {len(post_formacion):,}")
print(f"Postulantes Experiencia   : {len(post_experiencia):,}")
print(f"Postulantes Postulaciones : {len(post_postulaciones):,}")

"""####3.4.2. Intersección entre pares de datasets"""

post_formacion = set(formacion["postulante"].unique())
post_experiencia = set(experiencia["postulante"].unique())
post_postulaciones = set(postulaciones["postulante"].unique())

# ============================================================
# PASO 3.4.2. INTERSECCIÓN ENTRE DATASETS
# ============================================================

print("Formación ∩ Experiencia      :", len(post_formacion & post_experiencia))
print("Formación ∩ Postulaciones    :", len(post_formacion & post_postulaciones))
print("Experiencia ∩ Postulaciones  :", len(post_experiencia & post_postulaciones))

"""####3.4.3. Intersección de los tres datasets"""

# ============================================================
# PASO 3.4.3. POSTULANTES COMUNES A LOS TRES DATASETS
# ============================================================

post_comunes = (
    post_formacion &
    post_experiencia &
    post_postulaciones
)

print(f"Postulantes presentes en los tres datasets: {len(post_comunes):,}")

"""####3.4.4. Postulantes exclusivos"""

# ============================================================
# PASO 3.4.4. POSTULANTES EXCLUSIVOS
# ============================================================

solo_formacion = post_formacion - (post_experiencia | post_postulaciones)
solo_experiencia = post_experiencia - (post_formacion | post_postulaciones)
solo_postulaciones = post_postulaciones - (post_formacion | post_experiencia)

print(f"Solo Formación     : {len(solo_formacion):,}")
print(f"Solo Experiencia   : {len(solo_experiencia):,}")
print(f"Solo Postulaciones : {len(solo_postulaciones):,}")

"""####3.4.5. Resumen de integración"""

# ============================================================
# PASO 3.4.5. RESUMEN DE INTEGRACIÓN
# ============================================================

resumen = pd.DataFrame({
    "Dataset": ["Formación", "Experiencia", "Postulaciones"],
    "Postulantes únicos": [
        len(post_formacion),
        len(post_experiencia),
        len(post_postulaciones)
    ]
})

display(resumen)

print("\nPostulantes comunes a los tres datasets:", len(post_comunes))

"""#Módulo 4. Construcción del Perfil Académico

Consolidar la información académica de cada postulante en una única observación, generando variables descriptivas que representen su nivel educativo, diversidad de formación y áreas de conocimiento. Este proceso permitirá obtener un perfil académico estructurado para su integración posterior en la Analytical Base Table (ABT).

## 4.1. Copia del dataset
"""

# ============================================================
# MÓDULO 4. CONSTRUCCIÓN DEL PERFIL ACADÉMICO
# PASO 4.1. COPIA DEL DATASET
# ============================================================

formacion_abt = formacion.copy()

print("Registros:", len(formacion_abt))
print("Postulantes:", formacion_abt["postulante"].nunique())

"""##4.2. Verificar niveles de formación"""

# ============================================================
# PASO 4.2. NIVELES DE FORMACIÓN
# ============================================================

display(
    formacion_abt["nivel_formacion"]
    .value_counts()
    .sort_values(ascending=False)
)

"""##4.3. Construcción dinámica del perfil académico"""

# ============================================================
# PASO 4.3. CONSTRUCCIÓN DINÁMICA DEL PERFIL ACADÉMICO
# ============================================================

# ---------- Variables generales por postulante ----------

perfil_general = (
    formacion_abt
    .groupby("postulante")
    .agg(
        nivel_educativo=("nivel_educativo", "first"),
        total_formaciones=("titulo_academico", "count"),
        cantidad_areas=("area_conocimiento", "nunique"),
        cantidad_nbc=("codigo_nbc", "nunique")
    )
)

# ---------- Conteo dinámico por nivel de formación ----------

niveles_formacion = (
    pd.crosstab(
        formacion_abt["postulante"],
        formacion_abt["nivel_formacion"]
    )
)

# Renombrar columnas automáticamente

niveles_formacion.columns = [
    "cant_" + c.lower()
               .replace(" ", "_")
               .replace("-", "_")
               .replace("/", "_")
    for c in niveles_formacion.columns
]

# ---------- Integración ----------

perfil_academico = (
    perfil_general
    .join(niveles_formacion)
    .reset_index()
)

perfil_academico.head()

"""##4.4. Validación del perfil"""

print("Registros :", len(perfil_academico))
print("Postulantes:", perfil_academico["postulante"].nunique())

print("\nColumnas generadas:")

display(perfil_academico.columns)

"""## 4.5. Distribución de las variables académicas"""

# ============================================================
# PASO 4.5. DISTRIBUCIÓN DEL PERFIL ACADÉMICO
# ============================================================

# Variables generadas dinámicamente
variables_formacion = [
    col for col in perfil_academico.columns
    if col.startswith("cant_")
]

# Total de registros por nivel de formación
resumen_formacion = (
    perfil_academico[variables_formacion]
    .sum()
    .sort_values(ascending=False)
    .reset_index()
)

resumen_formacion.columns = [
    "Nivel de formación",
    "Total registros"
]

display(resumen_formacion)

"""##4.6. Guardar el perfil academico"""

# ============================================================
# PASO 4.6. GUARDAR EL PERFIL ACADÉMICO
# ============================================================

print("Dimensiones del perfil académico:")
print(perfil_academico.shape)

# Guardar para su integración posterior
perfil_academico.to_csv(
    "/content/perfil_academico.csv",
    index=False,
    encoding="utf-8-sig"
)

print("✔ Perfil académico guardado correctamente.")

"""##4.7. Verificación final del perfil académico"""

# ============================================================
# PASO 4.7. VALIDACIÓN FINAL DEL PERFIL ACADÉMICO
# ============================================================

# Reload perfil_academico from CSV in case the kernel was restarted
import pandas as pd
perfil_academico = pd.read_csv(
    "/content/perfil_academico.csv",
    encoding="utf-8-sig"
)

print("="*70)
print("PERFIL ACADÉMICO")
print("="*70)

print(f"Registros              : {len(perfil_academico):,}")
print(f"Postulantes únicos     : {perfil_academico['postulante'].nunique():,}")
print(f"Variables              : {perfil_academico.shape[1]}")

print("\nValores nulos por variable:\n")

display(
    perfil_academico.isnull()
    .sum()
    .to_frame("Nulos")
)

print("\n✔ Perfil académico listo para integrarse con la ABT.")

# Revisar el archivo perfil_academico.csv

academico = pd.read_csv("/content/perfil_academico.csv", encoding="utf-8-sig")

print("Dimensiones:", academico.shape)
print("Postulantes únicos:", academico["postulante"].nunique())

display(academico.head())

print("Registros del DataFrame en memoria:")
print(perfil_academico.shape)

print("\nPostulantes únicos:")
print(perfil_academico["postulante"].nunique())

print(formacion.shape)
print(formacion["postulante"].nunique())

"""#Módulo 5: Construcción del Perfil de Experiencia

##5.1. Copia del dataset
"""

# ============================================================
# MÓDULO 5. CONSTRUCCIÓN DEL PERFIL DE EXPERIENCIA
# PASO 5.1. COPIA DEL DATASET
# ============================================================

experiencia_abt = experiencia.copy()

print("Registros :", len(experiencia_abt))
print("Postulantes :", experiencia_abt["postulante"].nunique())

"""5.2. Conversión de fechas"""

# ============================================================
# PASO 5.2. CONVERSIÓN DE FECHAS
# ============================================================

experiencia_abt["experiencia_fecha_ingreso"] = pd.to_datetime(
    experiencia_abt["experiencia_fecha_ingreso"],
    errors="coerce"
)

experiencia_abt["experiencia_fecha_salida"] = pd.to_datetime(
    experiencia_abt["experiencia_fecha_salida"],
    errors="coerce"
)

print(experiencia_abt.dtypes)

"""##5.3. Validación de fechas"""

# ============================================================
# PASO 5.3. VALIDACIÓN DE FECHAS
# ============================================================

print("Fechas de ingreso nulas:",
      experiencia_abt["experiencia_fecha_ingreso"].isna().sum())

print("Fechas de salida nulas:",
      experiencia_abt["experiencia_fecha_salida"].isna().sum())

"""##5.4. Ordenamiento de los periodos laborales"""

# ============================================================
# PASO 5.4. ORDENAR EXPERIENCIAS
# ============================================================

experiencia_abt = experiencia_abt.sort_values(
    ["postulante",
     "experiencia_fecha_ingreso",
     "experiencia_fecha_salida"]
)

display(experiencia_abt.head())

"""##5.5. Construcción del Perfil de Experiencia Efectiva

Consolidar la trayectoria laboral de cada postulante calculando el tiempo efectivo de experiencia, eliminando periodos traslapados y generando indicadores descriptivos que serán incorporados a la ABT.
"""

# ============================================================
# PASO 5.5. PERFIL DE EXPERIENCIA EFECTIVA
# ============================================================

def construir_perfil_experiencia(grupo):

    # Ordenar cronológicamente
    grupo = grupo.sort_values("experiencia_fecha_ingreso")

    # Conservar objetos Timestamp
    intervalos = list(
        grupo[
            ["experiencia_fecha_ingreso",
             "experiencia_fecha_salida"]
        ]
        .dropna()
        .itertuples(index=False, name=None)
    )

    # Si no existen intervalos válidos
    if len(intervalos) == 0:

        return pd.Series({

            "total_experiencias": 0,
            "periodos_efectivos": 0,
            "dias_experiencia_efectiva": 0,
            "anios_experiencia_efectiva": 0,
            "fecha_primera_experiencia": pd.NaT,
            "fecha_ultima_experiencia": pd.NaT

        })

    # =====================================================
    # Fusionar periodos traslapados
    # =====================================================

    fusionados = []

    inicio, fin = intervalos[0]

    for nuevo_inicio, nuevo_fin in intervalos[1:]:

        # Ignorar registros inconsistentes
        if nuevo_fin < nuevo_inicio:
            continue

        if nuevo_inicio <= fin:

            fin = max(fin, nuevo_fin)

        else:

            fusionados.append((inicio, fin))

            inicio, fin = nuevo_inicio, nuevo_fin

    fusionados.append((inicio, fin))

    # =====================================================
    # Calcular días efectivos
    # =====================================================

    dias = sum(
        (fin - inicio).days + 1
        for inicio, fin in fusionados
    )

    return pd.Series({

        "total_experiencias": len(grupo),

        "periodos_efectivos": len(fusionados),

        "dias_experiencia_efectiva": dias,

        "anios_experiencia_efectiva": round(dias / 365.25, 2),

        "fecha_primera_experiencia": fusionados[0][0],

        "fecha_ultima_experiencia": fusionados[-1][1]

    })


# =====================================================
# Construcción del perfil
# =====================================================

perfil_experiencia = (
    experiencia_abt
    .groupby("postulante")
    .apply(construir_perfil_experiencia)
    .reset_index()
)

display(perfil_experiencia.head())

"""##5.6. Variables de duración de cada experiencia"""

# ============================================================
# PASO 5.6. DURACIÓN DE CADA EXPERIENCIA
# ============================================================

experiencia_abt["dias_experiencia"] = (
    experiencia_abt["experiencia_fecha_salida"] -
    experiencia_abt["experiencia_fecha_ingreso"]
).dt.days + 1

experiencia_abt["anios_experiencia"] = (
    experiencia_abt["dias_experiencia"] / 365.25
).round(2)

display(experiencia_abt.head())

"""##5.7. Estadísticos de la experiencia"""

# ============================================================
# PASO 5.7. ESTADÍSTICAS DE EXPERIENCIA
# ============================================================

estadisticas = (
    experiencia_abt
    .groupby("postulante")
    .agg(
        experiencia_promedio=("dias_experiencia","mean"),
        experiencia_maxima=("dias_experiencia","max"),
        experiencia_minima=("dias_experiencia","min")
    )
    .round(0)
    .reset_index()
)

display(estadisticas.head())

"""##5.8. Antigüedad laboral"""

# ============================================================
# PASO 5.8. ANTIGÜEDAD LABORAL
# ============================================================

perfil_experiencia["antiguedad_laboral_dias"] = (
    perfil_experiencia["fecha_ultima_experiencia"] -
    perfil_experiencia["fecha_primera_experiencia"]
).dt.days + 1

perfil_experiencia["antiguedad_laboral_anios"] = (
    perfil_experiencia["antiguedad_laboral_dias"] / 365.25
).round(2)

"""##5.9. Densidad laboral"""

# ============================================================
# PASO 5.9. DENSIDAD LABORAL
# ============================================================

perfil_experiencia["densidad_laboral"] = (
    perfil_experiencia["dias_experiencia_efectiva"] /
    perfil_experiencia["antiguedad_laboral_dias"]
).round(3)

perfil_experiencia["densidad_laboral"] = (
    perfil_experiencia["densidad_laboral"]
    .clip(upper=1)
)

"""Interpretación:

Cercano a 1 → trayectoria continua.
Cercano a 0 → largos períodos sin experiencia registrada.

##5.10. Integración del perfil
"""

# ============================================================
# PASO 5.10. INTEGRACIÓN DEL PERFIL
# ============================================================

perfil_experiencia = perfil_experiencia.merge(
    estadisticas,
    on="postulante",
    how="left"
)

perfil_experiencia.rename(columns={
    "experiencia_promedio":"duracion_promedio_experiencia",
    "experiencia_maxima":"duracion_maxima_experiencia",
    "experiencia_minima":"duracion_minima_experiencia"
}, inplace=True)

display(perfil_experiencia.head())

"""##5.11. Validación final"""

# ============================================================
# PASO 5.11. VALIDACIÓN FINAL
# ============================================================

print("="*70)
print("PERFIL DE EXPERIENCIA")
print("="*70)

print("Registros :", len(perfil_experiencia))
print("Postulantes :", perfil_experiencia["postulante"].nunique())
print("Variables :", perfil_experiencia.shape[1])

print("\nValores nulos")

display(
    perfil_experiencia.isnull()
    .sum()
    .to_frame("Nulos")
)

"""5.12. Estadísticos descriptivos"""

# ============================================================
# PASO 5.12. ESTADÍSTICAS DEL PERFIL DE EXPERIENCIA
# ============================================================

perfil_experiencia.describe(include="all").T

"""##5.13. Guardar el perfil"""

# ============================================================
# PASO 5.13. GUARDAR PERFIL DE EXPERIENCIA
# ============================================================

perfil_experiencia.to_csv(
    "/content/perfil_experiencia.csv",
    index=False,
    encoding="utf-8-sig"
)

print("Dimensiones del perfil de experiencia:")
print(perfil_experiencia.shape)

print("✔ Perfil de experiencia guardado correctamente.")

"""Este módulo incorpora un aspecto diferenciador respecto a una consolidación tradicional: el cálculo de la experiencia laboral efectiva. En lugar de sumar de forma directa la duración de cada registro, se implementó un algoritmo que identifica y fusiona periodos laborales traslapados, evitando la doble contabilización del tiempo trabajado. Esta estrategia genera una medida más precisa de la experiencia acumulada y mejora la calidad de las variables utilizadas para el entrenamiento del modelo predictivo.

#MÓDULO 6. PERFIL DEPARTICIPACION Y DESEMPEÑO EN LOS PROCESOS DE SELECCION

Consolidar el historial de postulaciones de cada aspirante, generando variables que describan su comportamiento en los procesos de selección y sus resultados, obteniendo un único registro por postulante para su integración posterior en la ABT.

Variables que construiremos

Las variables se pueden organizar en cuatro dimensiones.

| Dimensión     | Variables                                                       |
| ------------- | --------------------------------------------------------------- |
| Actividad     | total_postulaciones                                             |
| Participación | total_pruebas_presentadas, tipos_prueba                         |
| Desempeño     | pruebas_aprobadas, porcentaje_aprobacion                        |
| Resultados    | promedio_calificacion, maxima_calificacion, minima_calificacion |

##6.1. Copia del dataset
"""

# ============================================================
# MÓDULO 6. PERFIL DE POSTULACIONES
# PASO 6.1. COPIA DEL DATASET
# ============================================================

postulaciones_abt = postulaciones.copy()

print("Registros :", len(postulaciones_abt))
print("Postulantes :", postulaciones_abt["postulante"].nunique())

"""##6.2. Exploración inicial"""

# ============================================================
# PASO 6.2. EXPLORACIÓN DE VARIABLES
# ============================================================

display(postulaciones_abt.head())

print("\nTipos de datos\n")

print(postulaciones_abt.dtypes)

"""##6.3. Revisar las pruebas existentes"""

# ============================================================
# PASO 6.3. TIPOS DE PRUEBA
# ============================================================

tipos_prueba = (
    postulaciones_abt["tipo_prueba"]
    .value_counts()
    .reset_index()
)

tipos_prueba.columns = ["Tipo de prueba","Cantidad"]

display(tipos_prueba)

"""##6.4. Revisar la variable "aprobo"
"""

# ============================================================
# PASO 6.4. RESULTADO DE LAS PRUEBAS
# ============================================================

display(
    postulaciones_abt["aprobo"]
    .value_counts(dropna=False)
)

"""| Resultado |    Cantidad |  Porcentaje |
| --------- | ----------: | ----------: |
| True      |      63.130 | **63,13 %** |
| False     |      36.870 | **36,87 %** |
| **Total** | **100.000** |   **100 %** |

El 63,13 % de los registros corresponde a pruebas o etapas que fueron aprobadas.
El 36,87 % corresponde a pruebas no aprobadas.
No existen valores nulos ni categorías diferentes de True y False, por lo que la variable tiene buena calidad y puede utilizarse directamente para construir indicadores agregados.

##6.5. Analizar las calificaciones
"""

# ============================================================
# PASO 6.5. CALIFICACIONES
# ============================================================

print(postulaciones_abt["calificacion"].describe())

print("\nValores nulos:")

print(postulaciones_abt["calificacion"].isna().sum())

"""Esto nos indica que no todas las pruebas generan una calificación numérica.

En los concursos de la CNSC esto es completamente normal:

Algunas etapas únicamente verifican un requisito (por ejemplo, Verificación de Requisitos Mínimos) y su resultado es Aprobó / No aprobó.
Otras etapas (competencias, conocimientos, valoración de antecedentes, etc.) sí generan una calificación.

Por lo tanto, no podemos reemplazar los valores nulos de calificacion por cero, porque significaría que el postulante obtuvo una nota de 0 cuando en realidad esa prueba nunca fue calificable.

Ese es un criterio metodológico importante para dejar documentado en la tesis.

##6.6 Estandarización de tipos de prueba
"""

# ============================================================
# PASO 6.6. ESTANDARIZACIÓN DE TIPOS DE PRUEBA
# ============================================================

postulaciones_abt["tipo_prueba"] = (
    postulaciones_abt["tipo_prueba"]
    .replace({

        "Prueba de Competencias Funcionales":
            "Competencias Funcionales",

        "Prueba de Integridad":
            "Integridad",

        "Prueba de Valores e Integridad":
            "Integridad",

        "Prueba de Ejecución (Conductor clasificatoria)":
            "Prueba de Ejecución",

        "Prueba de ejecución (clasificatoria)":
            "Prueba de Ejecución",

        "Prueba ejecución (Eliminatoria)":
            "Prueba de Ejecución"

    })
)

display(
    postulaciones_abt["tipo_prueba"]
    .value_counts()
)

"""##6.7. Construcción dinámica de variables por tipo de prueba"""

# ============================================================
# PASO 6.7. VARIABLES POR TIPO DE PRUEBA
# ============================================================

# Crear tabla dinámica
pruebas = pd.crosstab(
    postulaciones_abt["postulante"],
    postulaciones_abt["tipo_prueba"]
)

# Renombrar columnas
pruebas.columns = [
    "cant_" +
    c.lower()
     .replace(" ", "_")
     .replace("á","a")
     .replace("é","e")
     .replace("í","i")
     .replace("ó","o")
     .replace("ú","u")
     .replace("(","")
     .replace(")","")
    for c in pruebas.columns
]

pruebas = pruebas.reset_index()

display(pruebas.head())

"""##6.8. Construcción del perfil general"""

# ============================================================
# PASO 6.8. CONSTRUCCIÓN DEL PERFIL DE PARTICIPACIÓN Y DESEMPEÑO
# ============================================================

perfil_postulaciones = (
    postulaciones_abt
    .groupby("postulante")
    .agg(
        # Actividad
        total_registros_pruebas=("id", "count"),
        total_empleos_postulados=("id", "nunique"),

        # Desempeño
        pruebas_aprobadas=("aprobo", "sum"),

        # Resultados de pruebas calificadas
        cantidad_pruebas_calificadas=("calificacion", "count"),
        puntaje_promedio=("calificacion", "mean"),
        puntaje_maximo=("calificacion", "max"),
        puntaje_minimo=("calificacion", "min")
    )
    .reset_index()
)

# Redondear el puntaje promedio
perfil_postulaciones["puntaje_promedio"] = (
    perfil_postulaciones["puntaje_promedio"].round(2)
)

display(perfil_postulaciones.head())

"""Variable 1. Cantidad de tipos de prueba presentados

"""

pruebas["cantidad_tipos_prueba"] = (
    pruebas.drop(columns="postulante")
           .gt(0)
           .sum(axis=1)
)

"""Variable 2. Total de pruebas presentadas"""

pruebas["total_pruebas"] = (
    pruebas.drop(columns=["postulante","cantidad_tipos_prueba"])
           .sum(axis=1)
)

"""##6.9. Variables derivadas"""

# ============================================================
# PASO 6.9. VARIABLES DERIVADAS DEL DESEMPEÑO
# ============================================================

# Pruebas no aprobadas
perfil_postulaciones["pruebas_no_aprobadas"] = (
    perfil_postulaciones["total_registros_pruebas"] -
    perfil_postulaciones["pruebas_aprobadas"]
)

# Porcentaje de aprobación
perfil_postulaciones["porcentaje_aprobacion"] = (
    perfil_postulaciones["pruebas_aprobadas"] /
    perfil_postulaciones["total_registros_pruebas"]
).round(3)

# Porcentaje de pruebas calificadas
perfil_postulaciones["porcentaje_pruebas_calificadas"] = (
    perfil_postulaciones["cantidad_pruebas_calificadas"] /
    perfil_postulaciones["total_registros_pruebas"]
).round(3)

display(perfil_postulaciones.head())

"""##6.10. Integración del perfil"""

# ============================================================
# PASO 6.10. INTEGRACIÓN DEL PERFIL DE POSTULACIONES
# ============================================================

perfil_postulaciones = perfil_postulaciones.merge(
    pruebas,
    on="postulante",
    how="left"
)

print("Dimensiones del perfil:")
print(perfil_postulaciones.shape)

display(perfil_postulaciones.head())

"""##6.11. Validación del Perfil de Participación y Desempeño"""

# ============================================================
# PASO 6.11. VALIDACIÓN DEL PERFIL
# ============================================================

print("="*70)
print("PERFIL DE PARTICIPACIÓN Y DESEMPEÑO")
print("="*70)

print("Registros :", len(perfil_postulaciones))
print("Postulantes :", perfil_postulaciones["postulante"].nunique())
print("Variables :", perfil_postulaciones.shape[1])

print("\nValores nulos")

display(
    perfil_postulaciones
    .isnull()
    .sum()
    .to_frame("Nulos")
)

"""##6.12. Estadísticas descriptivas"""

# ============================================================
# PASO 6.12. ESTADÍSTICAS DESCRIPTIVAS
# ============================================================

display(
    perfil_postulaciones.describe(include="all").T
)

"""##6.13. Guardar el perfil"""

# ============================================================
# PASO 6.13. GUARDAR PERFIL
# ============================================================

perfil_postulaciones.to_csv(
    "/content/perfil_postulaciones.csv",
    index=False,
    encoding="utf-8-sig"
)

print("Dimensiones del perfil:")
print(perfil_postulaciones.shape)

print("✔ Perfil de participación y desempeño guardado correctamente.")

"""#MÓDULO 7. CONSTRUCCIÓN DE LA ANALYTICAL BASE TABLE (ABT)

Integrar los perfiles Académico, Experiencia y Participación y Desempeño mediante el identificador único del postulante, obteniendo una única tabla analítica que concentre las características relevantes para el entrenamiento y evaluación de los modelos de Machine Learning.

##7.1. Cargar los perfiles consolidados
"""

# ============================================================
# MÓDULO 7. CONSTRUCCIÓN DE LA ABT
# PASO 7.1. CARGA DE PERFILES CONSOLIDADOS
# ============================================================

perfil_academico = pd.read_csv(
    "/content/perfil_academico.csv",
    encoding="utf-8-sig"
)

perfil_experiencia = pd.read_csv(
    "/content/perfil_experiencia.csv",
    encoding="utf-8-sig"
)

perfil_postulaciones = pd.read_csv(
    "/content/perfil_postulaciones.csv",
    encoding="utf-8-sig"
)

print("✔ Perfiles cargados correctamente.")

"""##7.2. Verificar dimensiones"""

# ============================================================
# PASO 7.2. DIMENSIONES DE LOS PERFILES
# ============================================================

print("="*70)
print("PERFILES CONSOLIDADOS")
print("="*70)

print("Académico      :", perfil_academico.shape)
print("Experiencia    :", perfil_experiencia.shape)
print("Postulaciones  :", perfil_postulaciones.shape)

"""##7.4. Validación de la intersección de los perfiles"""

# ============================================================
# PASO 7.4. VALIDACIÓN DE LA INTERSECCIÓN
# ============================================================

academicos = set(perfil_academico["postulante"])
experiencia = set(perfil_experiencia["postulante"])
postulaciones = set(perfil_postulaciones["postulante"])

interseccion = academicos & experiencia & postulaciones

print("="*70)
print("INTERSECCIÓN DE LOS TRES PERFILES")
print("="*70)

print(f"Académico      : {len(academicos):,}")
print(f"Experiencia    : {len(experiencia):,}")
print(f"Postulaciones  : {len(postulaciones):,}")

print("\nPostulantes comunes:", len(interseccion))

"""##7.5. Construcción de la ABT"""

# ============================================================
# PASO 7.5. CONSTRUCCIÓN DE LA ABT
# ============================================================

abt = (
    perfil_academico
    .merge(
        perfil_experiencia,
        on="postulante",
        how="inner"
    )
    .merge(
        perfil_postulaciones,
        on="postulante",
        how="inner"
    )
)

print("="*70)
print("ABT CONSTRUIDA")
print("="*70)

print("Registros :", len(abt))
print("Postulantes únicos :", abt["postulante"].nunique())
print("Variables :", abt.shape[1])

display(abt.head())

"""En la ABT aparecen:

puntaje_promedio   NaN
puntaje_maximo     NaN
puntaje_minimo     NaN

Esto no es un error.

Significa que esos postulantes nunca presentaron una prueba que generara calificación, por ejemplo únicamente participaron en la Verificación de Requisitos Mínimos.

Desde el punto de vista metodológico, estos valores faltantes contienen información y no deben eliminarse.

Mi recomendación será:

Mantener esos registros, En la etapa de preprocesamiento del modelo imputar:
puntaje_promedio = 0
puntaje_maximo = 0
puntaje_minimo = 0

Además, conviene crear una variable binaria como tiene_pruebas_calificadas, pero eso lo haremos en la fase de ingeniería de características.

##7.6 Validación de la ABT
"""

# ============================================================
# PASO 7.6. VALIDACIÓN DE LA ABT
# ============================================================

print("="*70)
print("VALIDACIÓN DE LA ABT")
print("="*70)

print(f"Registros                : {len(abt):,}")
print(f"Postulantes únicos       : {abt['postulante'].nunique():,}")
print(f"Variables                : {abt.shape[1]}")

print("\nDuplicados por postulante:")

duplicados = abt["postulante"].duplicated().sum()

print(duplicados)

print("\nTipos de datos")

display(abt.dtypes.to_frame("Tipo"))

"""##7.7 Análisis de valores nulos"""

# ============================================================
# PASO 7.7. ANÁLISIS DE VALORES NULOS
# ============================================================

nulos = pd.DataFrame({
    "Variable": abt.columns,
    "Nulos": abt.isnull().sum(),
    "% Nulos": (abt.isnull().mean()*100).round(2)
})

nulos = nulos.sort_values("% Nulos", ascending=False)

display(nulos)

"""##7.8  Estadísticos descriptivos"""

# ============================================================
# PASO 7.8. ESTADÍSTICAS DESCRIPTIVAS
# ============================================================

display(
    abt.describe(include="all").T
)

"""##7.9 Guardar la ABT"""

# ============================================================
# PASO 7.9. GUARDAR LA ABT
# ============================================================

abt.to_csv(
    "/content/ABT_Modelo_Predictivo.csv",
    index=False,
    encoding="utf-8-sig"
)

print("Dimensiones finales de la ABT:")
print(abt.shape)

print("✔ ABT guardada correctamente.")

"""Resultados obtenidos
Integración de perfiles

Se integraron los tres perfiles previamente construidos:

| Perfil                    | Postulantes |
| ------------------------- | ----------: |
| Académico                 |      29.587 |
| Experiencia               |      31.312 |
| Participación y desempeño |      43.705 |



La intersección entre los tres conjuntos produjo:

20.293 postulantes comunes

Este conjunto constituye la población definitiva para el entrenamiento del modelo predictivo.

Construcción de la ABT

Después de realizar los cruces mediante la variable postulante, se obtuvo una base analítica con:

20.293 registros
20.293 postulantes únicos
54 variables

Esto garantiza una relación 1 registro = 1 postulante, condición indispensable para los algoritmos supervisados de Machine Learning.

Variables incorporadas

La ABT reúne información proveniente de tres dimensiones.

Perfil académico

22 variables

Incluye información como:

nivel educativo máximo
número total de formaciones
cantidad de áreas de conocimiento
cantidad de NBC
número de títulos por nivel de formación
bachiller
técnico
tecnólogo
profesional
especialización
maestría
doctorado
educación informal
entre otras.
Perfil laboral

13 variables

Incluye indicadores como:

número de experiencias laborales
años efectivos de experiencia
días efectivos trabajados
antigüedad laboral
duración promedio de contratos
duración máxima
duración mínima
densidad laboral
fecha de primera experiencia
fecha de última experiencia
Perfil de participación y desempeño

21 variables

Entre ellas:

número de postulaciones
número de empleos postulados
pruebas aprobadas
pruebas no aprobadas
porcentaje de aprobación
porcentaje de pruebas calificadas
puntaje promedio
puntaje máximo
puntaje mínimo
número de pruebas por tipo
total de pruebas
Validación de la ABT

La validación permitió comprobar que:

✔ No existen postulantes duplicados.

✔ Todas las variables fueron correctamente integradas.

✔ La llave primaria del modelo corresponde al identificador del postulante.

Valores faltantes

Únicamente se identificaron valores faltantes en tres variables:

| Variable         | % nulos |
| ---------------- | ------: |
| puntaje_promedio | 42.95 % |
| puntaje_maximo   | 42.95 % |
| puntaje_minimo   | 42.95 % |

Este comportamiento era esperado, ya que no todos los postulantes alcanzaron pruebas con calificación numérica. En muchos casos únicamente participaron en la etapa de verificación de requisitos mínimos, la cual registra aprobación o rechazo, pero no genera puntaje cuantitativo.

Por tanto, estos valores no corresponden a errores de calidad del dato, sino a la naturaleza del proceso de selección.

**Características de la base final**

La ABT presenta las siguientes características:

20.293 observaciones.
54 variables explicativas.
Información consolidada de formación, experiencia y desempeño.
Un registro por postulante.
Sin registros duplicados.
Lista para las etapas de preprocesamiento, ingeniería de variables, selección de atributos y entrenamiento de modelos predictivos.

#MÓDULO 8. ANÁLISIS EXPLORATORIO DE DATOS (EDA)

Realizar un análisis exploratorio sobre la Base Analítica (ABT) consolidada para comprender la estructura, distribución, calidad y comportamiento de las variables que conformarán el modelo predictivo.

##8.1 Cargar la ABT
"""

# ============================================================
# MÓDULO 8. ANÁLISIS EXPLORATORIO DE DATOS (EDA)
# 8.1 CARGAR LA ABT
# ============================================================

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

# Cargar la ABT construida
abt = pd.read_csv("/content/ABT_Modelo_Predictivo.csv")

print("="*70)
print("ANALYTICAL BASE TABLE")
print("="*70)

print("Dimensiones:", abt.shape)
print("Postulantes:", abt["postulante"].nunique())

"""##8.2 Información general

Este paso nos permitirá conocer rápidamente la estructura de la base.
"""

# ============================================================
# 8.2 INFORMACIÓN GENERAL
# ============================================================

print("="*70)
print("INFORMACIÓN GENERAL")
print("="*70)

abt.info()

print("\nMemoria utilizada:")

print(round(abt.memory_usage(deep=True).sum()/1024**2,2),"MB")

"""Resultado:

20.293 postulantes
54 variables
42 enteras
9 decimales
3 categóricas
11.38 MB

Interpretación

La ABT posee un tamaño adecuado para el entrenamiento de modelos de Machine Learning. La mayor parte de las variables son numéricas, lo que facilita su utilización en algoritmos supervisados sin requerir transformaciones complejas.

##8.3 Tipos de variables
"""

# ============================================================
# 8.3 TIPOS DE VARIABLES
# ============================================================

tipos = abt.dtypes.value_counts().reset_index()

tipos.columns=["Tipo","Cantidad"]

display(tipos)

"""Predominan las variables cuantitativas (94.4%), mientras que únicamente tres corresponden a variables categóricas, las cuales posteriormente serán codificadas mediante técnicas de transformación para su incorporación en los modelos predictivos.

##8.4 Estadística descriptiva

Aquí obtendremos una visión general de todas las variables numéricas.
"""

# ============================================================
# 8.4 ESTADÍSTICA DESCRIPTIVA
# ============================================================

estadisticas = (
    abt
    .describe()
    .T
    .round(2)
)

display(estadisticas)

"""de estos resultados se tiene que
* Formación

  * Promedio de 4 formaciones académicas
  * Máximo de 150

* Experiencia
  * Promedio de 6 años
  * Máximo de 44.8 años

* Pruebas

  * Promedio de aprobación 54.9%
  * Promedio de 2.56 pruebas

Interpretación

La población presenta una alta heterogeneidad en formación y experiencia laboral. Mientras algunos postulantes cuentan únicamente con una formación registrada, otros presentan trayectorias académicas considerablemente extensas. Asimismo, existe una importante dispersión en la experiencia laboral, lo que evidencia perfiles muy diversos.

##8.5 Distribución de variables categóricas
"""

# ============================================================
# 8.5 NIVEL EDUCATIVO
# ============================================================

nivel = (
    abt["nivel_educativo"]
    .value_counts()
    .reset_index()
)

nivel.columns=["Nivel educativo","Cantidad"]

display(nivel)

"""De estos resultados se puede interpretar que:



| Variable          | Interpretación                                                                                                                 |
| ----------------- | ------------------------------------------------------------------------------------------------------------------------------ |
| total_formaciones | media 4.03, mediana 3.0. La mayoría posee entre 2 y 5 registros de formación. Existen valores extremos de hasta 150 registros. |
| cantidad_areas    | media 0.78. La mayoría pertenece únicamente a un área del conocimiento.                                                        |
| cantidad_nbc      | media 0.65. Normalmente un postulante registra un único núcleo básico del conocimiento.                                        |

Variables de experiencia   

| Variable                   | Interpretación                                                |
| -------------------------- | ------------------------------------------------------------- |
| total_experiencias         | media 3.05 experiencias laborales.                            |
| periodos_efectivos         | media 2.67 períodos laborales después de eliminar traslapes.  |
| anios_experiencia_efectiva | promedio cercano a 6 años.                                    |
| densidad_laboral           | media 0.86, indicando continuidad laboral relativamente alta. |


Variables de desempeño

| Variable              | Interpretación                                    |
| --------------------- | ------------------------------------------------- |
| pruebas_aprobadas     | media 1.64 pruebas aprobadas.                     |
| porcentaje_aprobacion | promedio 54.9%.                                   |
| puntaje_promedio      | 30.68 únicamente para registros con calificación. |

##8.6 Distribución de variables categóricas
"""

display(
    abt["nivel_educativo"]
    .value_counts()
    .reset_index()
    .rename(columns={
        "index":"Nivel educativo",
        "nivel_educativo":"Cantidad"
    })
)

(
    abt["nivel_educativo"]
    .value_counts(normalize=True)
    .mul(100)
    .round(2)
)

"""Interpretación

La distribución confirma una marcada concentración de postulantes en niveles profesionales y técnicos, mientras que los niveles de doctorado y postdoctorado representan una proporción mínima dentro de la población analizada.

##8.7 Valores faltantes

| Variable         | % nulos |
| ---------------- | ------- |
| puntaje_promedio | 42.95%  |
| puntaje_maximo   | 42.95%  |
| puntaje_minimo   | 42.95%  |

Los únicos valores faltantes corresponden a las variables derivadas de la calificación obtenida en las pruebas. Esto ocurre porque una proporción importante de registros pertenece a la etapa de Verificación de Requisitos Mínimos, proceso que no genera puntaje numérico. No se identificaron valores faltantes en las variables académicas, laborales ni de participación, lo cual evidencia una adecuada calidad de los datos para el entrenamiento del modelo.

##8.8 Detección de valores extremos (Outliers)
"""

variables = [
    "total_formaciones",
    "anios_experiencia_efectiva",
    "puntaje_promedio",
    "porcentaje_aprobacion"
]

abt[variables].boxplot(figsize=(12,5))
plt.xticks(rotation=45)
plt.show()

"""##8.9 Correlación entre variables numéricas"""

import seaborn as sns
import matplotlib.pyplot as plt

corr = abt.select_dtypes(include="number").corr()

plt.figure(figsize=(18,14))
sns.heatmap(
    corr,
    cmap="RdBu_r",
    center=0
)
plt.title("Correlación entre variables")
plt.show()

"""##8.10 Distribución de la variable objetivo"""

abt["porcentaje_aprobacion"].hist(bins=20)

abt["pruebas_aprobadas"].hist()

"""Conclusiones


La construcción de la Tabla Analítica Base (ABT) permitió integrar en una única estructura la información académica, la experiencia laboral y el historial de participación en procesos de selección de cada postulante. Una vez consolidada esta base, fue posible realizar un análisis exploratorio integral sobre la totalidad de las variables que conformarán el modelo predictivo.

El EDA evidenció que la ABT presenta una estructura consistente, con un registro único por postulante, ausencia de duplicados y una adecuada calidad de los datos para la mayoría de las variables. Asimismo, se identificó que los valores nulos se concentran únicamente en las variables relacionadas con puntajes de pruebas, situación esperada debido a que no todos los aspirantes alcanzaron etapas del proceso donde dichas evaluaciones generan una calificación numérica.

Desde la perspectiva descriptiva, el análisis permitió caracterizar el perfil general de los aspirantes. Se observó un predominio de postulantes con formación profesional y bachiller, una experiencia laboral mediana cercana a cuatro años, una alta continuidad en las trayectorias laborales reflejada en la densidad laboral y una participación relativamente limitada en procesos de selección, ya que la mayoría registra una sola postulación y pocas pruebas asociadas.

Las distribuciones de las variables revelaron la presencia de valores atípicos en indicadores como número de formaciones y años de experiencia, comportamiento esperado en datos administrativos que representan trayectorias laborales altamente heterogéneas. Igualmente, la matriz de correlación permitió identificar relaciones fuertes entre variables derivadas de una misma dimensión, especialmente aquellas asociadas con experiencia laboral y desempeño en pruebas, información que será considerada posteriormente para evitar redundancia y multicolinealidad durante el modelado.

En conjunto, el análisis exploratorio confirmó que la ABT constituye una representación consistente del perfil de los aspirantes y proporcionó un entendimiento profundo sobre la distribución, calidad y relaciones existentes entre las variables. Este conocimiento resulta fundamental antes de iniciar el desarrollo de modelos predictivos, ya que permite definir estrategias adecuadas de preparación de datos, selección de variables y construcción de características, incrementando la robustez y confiabilidad de las etapas posteriores del proyecto.

"""